# Generated by Django 6.0.7 on 2026-07-30 23:39

import apps.orders.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='número')),
                ('client_name', models.CharField(max_length=150, verbose_name='nome do cliente')),
                ('client_whatsapp', models.CharField(max_length=25, verbose_name='WhatsApp do cliente')),
                ('description', models.TextField(verbose_name='descrição')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor total')),
                ('payment_status', models.CharField(choices=[('nao_pago', 'Não pago'), ('parcial', 'Parcialmente pago'), ('pago', 'Pago')], default='nao_pago', max_length=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor pago')),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=20, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='entrega prevista')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('stage', models.CharField(choices=[('novo', 'Pedido novo'), ('preparacao', 'Preparação de arquivo'), ('producao', 'Em produção'), ('pronto', 'Pronto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='novo', max_length=15)),
                ('stage_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_orders',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='nome original')),
                ('file', models.FileField(blank=True, upload_to=apps.orders.models.attachment_upload_path)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_order_attachments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='orders.order')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_order_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_order_attachments',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_order_history',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_order_notes',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(blank=True, choices=[('novo', 'Pedido novo'), ('preparacao', 'Preparação de arquivo'), ('producao', 'Em produção'), ('pronto', 'Pronto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=15, null=True)),
                ('new_stage', models.CharField(choices=[('novo', 'Pedido novo'), ('preparacao', 'Preparação de arquivo'), ('producao', 'Em produção'), ('pronto', 'Pronto'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_history', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_stage_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_order_stage_history',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage'], name='pf_order_stage'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='pf_order_payment'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='pf_order_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['responsible'], name='pf_order_responsible'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['due_at'], name='pf_order_due'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage', 'due_at'], name='pf_order_stage_due'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stage', 'stage_updated_at'], name='pf_order_stage_move'),
        ),
        migrations.AddIndex(
            model_name='orderattachment',
            index=models.Index(fields=['order', 'removed_at'], name='pf_attachment_active'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order', 'created_at'], name='pf_history_order_date'),
        ),
        migrations.AddIndex(
            model_name='ordernote',
            index=models.Index(fields=['order', 'created_at'], name='pf_note_order_date'),
        ),
        migrations.AddIndex(
            model_name='orderstagehistory',
            index=models.Index(fields=['order', 'created_at'], name='pf_stage_order_date'),
        ),
    ]
