# Generated by Django 6.0.7 on 2026-08-05 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote_token',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, verbose_name='token do orçamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('novo', 'Novo Pedido'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('pre_impressao', 'Pré-Impressão'), ('em_producao', 'Em Produção'), ('pronto_retirada', 'Pronto pra Retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='novo', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='new_stage',
            field=models.CharField(choices=[('novo', 'Novo Pedido'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('pre_impressao', 'Pré-Impressão'), ('em_producao', 'Em Produção'), ('pronto_retirada', 'Pronto pra Retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstagehistory',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('novo', 'Novo Pedido'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('pre_impressao', 'Pré-Impressão'), ('em_producao', 'Em Produção'), ('pronto_retirada', 'Pronto pra Retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], max_length=30, null=True),
        ),
    ]
