# Generated by Django 6.0.7 on 2026-08-16 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_repair_legacy_receipt_snapshot_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=10, verbose_name='turno de produção'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=40, verbose_name='cor do produto'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=10, verbose_name='tamanho do produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='kind',
            field=models.CharField(choices=[('material', 'Material / DTF'), ('produto', 'Produto / Camisa'), ('servico', 'Serviço Extra'), ('ajuste', 'Ajuste')], default='material', max_length=12),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shift'], name='pf_order_shift'),
        ),
    ]
