# Generated by Django 6.0.7 on 2026-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shift_orderitem_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shift',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=10, verbose_name='turno de produção'),
        ),
    ]
