# Generated by Django 6.0.7 on 2026-08-19 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_description'),
        ('payments', '0003_cliente_metros_saldo_cliente_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vinculados', to='payments.cliente', verbose_name='cliente cadastrado'),
        ),
        migrations.AddField(
            model_name='order',
            name='correction_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='motivo da correção / defeito'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='abatimento / entrada já paga'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='pedido de correção / garantia'),
        ),
    ]
