# Generated by Django 6.0.7 on 2026-08-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cliente_order_correction_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_whatsapp',
            field=models.BooleanField(default=False, verbose_name='cliente avisado no WhatsApp'),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_whatsapp_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cliente avisado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_whatsapp_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='cliente avisado por'),
        ),
    ]
