# Generated by Django 6.1 on 2026-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_notified_whatsapp_order_notified_whatsapp_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('na_retirada', 'Pagamento na Retirada'), ('saldo_credito', 'Saldo do Plano / Crédito'), ('outro', 'Outro')], max_length=20, null=True),
        ),
    ]
