# Generated by Django 6.1 on 2026-08-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('cartao', 'Cartão (Geral)'), ('dinheiro', 'Dinheiro (À Vista)'), ('transferencia', 'Transferência'), ('na_retirada', 'Pagamento na Retirada'), ('saldo_credito', 'Saldo do Plano / Crédito'), ('outro', 'Outro')], max_length=20, null=True),
        ),
    ]
