# Generated by Django 6.1 on 2026-09-20 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='motivo do abatimento / desconto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('cartao', 'Cartão (Geral)'), ('dinheiro', 'Dinheiro (À Vista)'), ('transferencia', 'Transferência'), ('na_retirada', 'Pagamento na Retirada'), ('saldo_credito', 'Saldo do Plano / Crédito'), ('multiplo', 'Múltiplas Formas'), ('outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('cartao', 'Cartão (Geral)'), ('dinheiro', 'Dinheiro (À Vista)'), ('transferencia', 'Transferência'), ('na_retirada', 'Pagamento na Retirada'), ('saldo_credito', 'Saldo do Plano / Crédito'), ('multiplo', 'Múltiplas Formas'), ('outro', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor pago')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='pedido')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_order_payments', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Pagamento do Pedido',
                'verbose_name_plural': 'Pagamentos do Pedido',
                'db_table': 'pf_order_payments',
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='pf_pay_order_created'), models.Index(fields=['payment_method'], name='pf_pay_method')],
            },
        ),
    ]
