# Generated by Django 6.0.7 on 2026-07-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='descrição')),
                ('category', models.CharField(choices=[('material', 'Material'), ('manutencao', 'Manutenção'), ('energia', 'Energia'), ('funcionarios', 'Funcionários'), ('transporte', 'Transporte'), ('aluguel', 'Aluguel'), ('impostos', 'Impostos'), ('outros', 'Outros')], max_length=20, verbose_name='categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('expense_date', models.DateField(verbose_name='data da despesa')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=12)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_expenses',
                'ordering': ['-expense_date', '-pk'],
                'indexes': [models.Index(fields=['expense_date', 'status'], name='pf_expense_date_stat'), models.Index(fields=['status', 'expense_date'], name='pf_expense_status_dt'), models.Index(fields=['category'], name='pf_expense_category')],
            },
        ),
    ]
