# Generated by Django 6.1 on 2026-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário'), ('dev', 'Desenvolvedor')], default='funcionario', max_length=20, verbose_name='perfil'),
        ),
    ]
