# Generated by Django 6.0.7 on 2026-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(choices=[('administracao', 'Administração / Geral'), ('atendimento', 'Atendimento / Vendas (Rats, Meno)'), ('producao', 'Pré-Impressão / Produção (Paula)')], default='administracao', max_length=20, verbose_name='setor'),
        ),
    ]
