# Generated by Django 6.0.7 on 2026-08-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='início da sessão atual'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='última atividade'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_device',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='dispositivo'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_page',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='última página acessada'),
        ),
    ]
