# Generated by Django 6.1 on 2026-08-30 23:14

from django.db import migrations, models


def seed_default_settings(apps, schema_editor):
    SystemSetting = apps.get_model('accounts', 'SystemSetting')
    defaults = [
        {
            "key": "cash_register",
            "name": "Módulo de Fechamento de Caixa",
            "is_active": False,
            "description": "Controla o acesso à tela de conciliação diária de caixa (/reports/caixa/). Se desmarcado (bloqueado), exibe a tela institucional de indisponibilidade.",
        },
        {
            "key": "online_timers_all",
            "name": "Cronômetro de Usuários para Todos",
            "is_active": False,
            "description": "Se desmarcado (bloqueado), o cronômetro digital em tempo real fica restrito ao Desenvolvedor e Administrador.",
        },
        {
            "key": "backups_module",
            "name": "Módulo de Backups Geral",
            "is_active": False,
            "description": "Se desmarcado (bloqueado), o módulo de backups fica restrito estritamente ao Desenvolvedor.",
        },
    ]
    for item in defaults:
        SystemSetting.objects.get_or_create(key=item["key"], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_current_login_at_user_last_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='chave de sistema')),
                ('name', models.CharField(max_length=100, verbose_name='nome da funcionalidade')),
                ('is_active', models.BooleanField(default=True, help_text='Se marcado, a funcionalidade estará liberada para uso normal.', verbose_name='desbloqueado / ativo')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição / observação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Controle de Funcionalidade',
                'verbose_name_plural': 'Controle de Funcionalidades & Bloqueios',
                'db_table': 'pf_system_settings',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_default_settings, migrations.RunPython.noop),
    ]
