# Generated by Django 6.0.7 on 2026-08-26 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='caminho do arquivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('backup_type', models.CharField(choices=[('db_only', 'Banco de Dados (.sql.gz)'), ('full_with_media', 'Completo (Banco + Mídias .zip)')], default='db_only', max_length=30, verbose_name='tipo de backup')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual (Via Painel)'), ('automatic', 'Automático (Rotina Madrugada)')], default='manual', max_length=30, verbose_name='origem')),
                ('storage_location', models.CharField(choices=[('local', 'Armazenamento Local'), ('google_drive', 'Google Drive'), ('local_and_drive', 'Local e Google Drive')], default='local', max_length=30, verbose_name='local de armazenamento')),
                ('gdrive_file_id', models.CharField(blank=True, max_length=255, verbose_name='ID no Google Drive')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, verbose_name='hash SHA-256')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('in_progress', 'Em Execução')], db_index=True, default='success', max_length=30, verbose_name='situação')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data de criação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_generated', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backup',
                'db_table': 'pf_backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pf_bkp_status_created'), models.Index(fields=['trigger_type', 'created_at'], name='pf_bkp_trigger_created')],
            },
        ),
    ]
