<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php';require_login();$user=current_user();
if(is_post()){
  validate_csrf($_POST['csrf_token']??null);$action=$_POST['action']??'';
  try{if($action==='name'){$name=trim((string)($_POST['nome']??''));if(mb_strlen($name)<3||mb_strlen($name)>120)throw new RuntimeException('Informe um nome entre 3 e 120 caracteres.');db()->prepare('UPDATE usuarios SET nome=? WHERE id=?')->execute([$name,$user['id']]);audit('edicao_perfil','usuario',(int)$user['id']);flash('success','Nome atualizado.');}
  elseif($action==='password'){$current=(string)($_POST['senha_atual']??'');$new=(string)($_POST['nova_senha']??'');$confirm=(string)($_POST['confirmar_senha']??'');$s=db()->prepare('SELECT senha FROM usuarios WHERE id=?');$s->execute([$user['id']]);if(!password_verify($current,(string)$s->fetchColumn()))throw new RuntimeException('A senha atual não confere.');if(strlen($new)<8||$new!==$confirm)throw new RuntimeException('A nova senha deve ter 8 caracteres ou mais e ser confirmada corretamente.');db()->prepare('UPDATE usuarios SET senha=?,forcar_troca_senha=0 WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$user['id']]);audit('alteracao_senha','usuario',(int)$user['id']);flash('success','Senha atualizada com sucesso.');}
  else throw new RuntimeException('Ação inválida.');}catch(Throwable $e){flash('error',$e instanceof RuntimeException?$e->getMessage():'Não foi possível atualizar o perfil.');}redirect('perfil/index.php');
}
$page_title='Meu perfil';require_once __DIR__ . '/../includes/header.php';$user=current_user();
?>
<div class="grid two-col"><section class="card form-card"><div class="section-heading"><div><h2>Dados pessoais</h2><p>E-mail: <?=e($user['email'])?></p></div></div><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="name"><label>Nome<input name="nome" value="<?=e($user['nome'])?>" required></label><div class="form-actions"><button class="btn btn-primary">Salvar nome</button></div></form></section><section class="card form-card"><div class="section-heading"><div><h2>Alterar senha</h2><?php if($user['forcar_troca_senha']):?><p class="text-danger">A troca de senha é obrigatória antes de continuar.</p><?php endif;?></div></div><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="password"><div class="form-grid"><label class="full">Senha atual<input type="password" name="senha_atual" autocomplete="current-password" required></label><label>Nova senha<input type="password" name="nova_senha" autocomplete="new-password" minlength="8" required></label><label>Confirmar nova senha<input type="password" name="confirmar_senha" autocomplete="new-password" minlength="8" required></label></div><div class="form-actions"><button class="btn btn-primary">Alterar senha</button></div></form></section></div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
