<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php'; require_login();
if (!is_post()) redirect('producao/index.php'); validate_csrf($_POST['csrf_token']??null); $id=(int)($_POST['pedido_id']??0); $order=order_by_id($id);
if (!can_access_order($order)) { http_response_code(404); exit('Pedido não encontrado.'); }
try {
  $nome=trim((string)($_POST['cliente_nome']??''));$whats=preg_replace('/\D/','',(string)($_POST['cliente_whatsapp']??''));$descricao=trim((string)($_POST['descricao']??''));$total=money_to_float((string)($_POST['valor_total']??''));$status=(string)($_POST['status_pagamento']??'');$pago=money_to_float((string)($_POST['valor_pago']??''));$forma=(string)($_POST['forma_pagamento']??'');$prioridade=(string)($_POST['prioridade']??'normal');
  if(mb_strlen($nome)<2||strlen($whats)<10||mb_strlen($descricao)<3||$total<=0||!valid_enum($status,payment_labels())||!in_array($prioridade,['normal','urgente'],true)||!in_array($forma,['','pix','cartao','dinheiro','transferencia','outro'],true)) throw new RuntimeException('Há dados inválidos no formulário.');
  if($status==='pago')$pago=$total;if($status==='nao_pago')$pago=0;if(($status==='parcial'&&($pago<=0||$pago>=$total))||$pago>$total)throw new RuntimeException('O valor pago não condiz com a situação selecionada.');
  $due=trim((string)($_POST['previsao_entrega']??''));$due=$due!==''?(new DateTime($due))->format('Y-m-d H:i:s'):null; $responsavel=$order['responsavel_id'];
  if(is_admin()){ $candidate=(int)($_POST['responsavel_id']??0);$responsavel=$candidate?:null;if($responsavel){$s=db()->prepare('SELECT id FROM usuarios WHERE id=? AND ativo=1');$s->execute([$responsavel]);if(!$s->fetch())throw new RuntimeException('Responsável inválido.');} }
  $before=['status_pagamento'=>$order['status_pagamento'],'valor_pago'=>$order['valor_pago'],'responsavel_id'=>$order['responsavel_id']];$pdo=db();$pdo->beginTransaction();
  $pdo->prepare('UPDATE pedidos SET cliente_nome=?,cliente_whatsapp=?,descricao=?,valor_total=?,status_pagamento=?,valor_pago=?,forma_pagamento=?,previsao_entrega=?,prioridade=?,observacoes_internas=?,responsavel_id=? WHERE id=?')->execute([$nome,$whats,$descricao,$total,$status,$pago,$forma?:null,$due,$prioridade,trim((string)($_POST['observacoes_internas']??''))?:null,$responsavel,$id]);
  $user=current_user();$pdo->prepare('INSERT INTO pedido_historico (pedido_id,usuario_id,acao,descricao) VALUES (?, ?, "edicao", "Informações do pedido atualizadas.")')->execute([$id,$user['id']]);store_order_uploads($id,$_FILES['arquivos']??[],$user['id']);$pdo->commit();
  if($order['status_pagamento']!==$status||$order['valor_pago']!=$pago)notify_role('administrador','Pagamento atualizado',$order['numero'].' teve seu pagamento atualizado.','producao/detalhes.php?id='.$id,'financeiro');if($responsavel&&$responsavel!=$order['responsavel_id'])notify_user((int)$responsavel,'Pedido atribuído',$order['numero'].' foi atribuído a você.','producao/detalhes.php?id='.$id);audit('edicao','pedido',$id,$before,['status_pagamento'=>$status,'valor_pago'=>$pago,'responsavel_id'=>$responsavel]);flash('success','Pedido atualizado.');
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Pedido editar: '.$e->getMessage());flash('error',$e instanceof RuntimeException?$e->getMessage():'Não foi possível atualizar o pedido.');}
redirect('producao/detalhes.php?id='.$id);
