# Generated by Django 6.0.7 on 2026-07-30 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stone', max_length=50)),
                ('type', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão')], max_length=10)),
                ('external_identifier', models.CharField(blank=True, max_length=190, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pendente', max_length=50)),
                ('pix_copy_paste', models.TextField(blank=True)),
                ('checkout_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='orders.order')),
            ],
            options={
                'db_table': 'pf_charges',
                'indexes': [models.Index(fields=['order'], name='pf_charge_order'), models.Index(fields=['external_identifier'], name='pf_charge_external')],
            },
        ),
    ]
