# Generated by Django 6.0.7 on 2026-08-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_description'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cpf_cnpj', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=25, null=True, verbose_name='telefone')),
                ('stone_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Cliente Stone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'pf_clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_token_id', models.CharField(max_length=100, verbose_name='Token Stone')),
                ('bandeira', models.CharField(blank=True, max_length=50, verbose_name='bandeira')),
                ('ultimos_4', models.CharField(max_length=4, verbose_name='últimos 4 dígitos')),
                ('validade', models.CharField(blank=True, max_length=10, verbose_name='validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='payments.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'db_table': 'pf_metodos_pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Pagamento Stone')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão')], default='pix', max_length=20, verbose_name='método')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhado', 'Falhado'), ('cancelado', 'Cancelado')], default='pendente', max_length=50, verbose_name='situação')),
                ('parcelas', models.IntegerField(default=1, verbose_name='parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='payments.cliente', verbose_name='cliente')),
                ('pedido_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_stone', to='orders.order', verbose_name='pedido de referência')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pf_pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente'], name='pf_pag_cliente'), models.Index(fields=['stone_payment_id'], name='pf_pag_stone_id'), models.Index(fields=['status'], name='pf_pag_status')],
            },
        ),
    ]
