# Generated by Django 6.0.7 on 2026-08-19 03:49

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cliente_metodopagamento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metros_saldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Metros contratados no Plano de Volume', max_digits=10, verbose_name='saldo em metros do pacote'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='observações do cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preco_especial_metro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço diferenciado do metro de DTF (ex: R$ 35,00)', max_digits=10, null=True, verbose_name='preço especial DTF/metro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo financeiro para abatimento em pedidos', max_digits=12, verbose_name='saldo em créditos (R$)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='telefone / WhatsApp'),
        ),
        migrations.CreateModel(
            name='ClienteArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do arquivo / descrição')),
                ('arquivo', models.FileField(upload_to=apps.payments.models.cliente_upload_path, verbose_name='arquivo')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_registrados', to='payments.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Arquivo Registrado do Cliente',
                'verbose_name_plural': 'Arquivos Registrados dos Clientes',
                'db_table': 'pf_cliente_arquivos',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
