# Generated by Django 6.1.1 on 2026-09-22 00:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cliente_metros_saldo_cliente_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneLogIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('REQUEST', 'Request'), ('RESPONSE', 'Response'), ('DEBUG', 'Debug')], db_index=True, default='INFO', max_length=15)),
                ('tipo_evento', models.CharField(db_index=True, max_length=64)),
                ('mensagem', models.TextField()),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('charge_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_type', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('error_parameter', models.CharField(blank=True, max_length=120)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('detalhes_extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Log de Integração Stone',
                'verbose_name_plural': 'Logs de Integração Stone',
                'db_table': 'pf_stone_logs',
                'ordering': ['-timestamp', '-pk'],
                'indexes': [models.Index(fields=['trace_id', 'timestamp'], name='pf_stone_log_tr_ts_idx'), models.Index(fields=['nivel', 'timestamp'], name='pf_stone_log_nv_ts_idx'), models.Index(fields=['order_id', 'timestamp'], name='pf_stone_log_ord_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoneMetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_payment_method_id', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('cartao', 'Cartão')], default='cartao', max_length=20)),
                ('bandeira', models.CharField(blank=True, max_length=30)),
                ('ultimos_4', models.CharField(blank=True, max_length=4)),
                ('validade_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('validade_ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stone_metodos_pagamento', to='payments.cliente')),
            ],
            options={
                'verbose_name': 'Método de Pagamento Stone (Teste)',
                'verbose_name_plural': 'Métodos de Pagamento Stone (Teste)',
                'db_table': 'pf_stone_metodos_pagamento',
                'ordering': ['-ativo', '-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StonePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=120, verbose_name='Nome do Cliente')),
                ('cliente_documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('cliente_email', models.CharField(blank=True, max_length=120, verbose_name='E-mail')),
                ('cliente_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('stone_payment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stone_order_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stone_transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=12)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('referencia', models.CharField(max_length=160)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('pix_qr_code_url', models.URLField(blank=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_started_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stone_pagamentos', to='payments.cliente')),
            ],
            options={
                'verbose_name': 'Pagamento Stone (Teste)',
                'verbose_name_plural': 'Pagamentos Stone (Teste)',
                'db_table': 'pf_stone_pagamentos',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StoneEventoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('descricao', models.TextField()),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stone_eventos_pagamento', to='payments.cliente')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='payments.stonepagamento')),
            ],
            options={
                'verbose_name': 'Evento Stone (Teste)',
                'verbose_name_plural': 'Eventos Stone (Teste)',
                'db_table': 'pf_stone_eventos',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='stonepagamento',
            index=models.Index(fields=['status', 'created_at'], name='pf_stone_pag_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stonepagamento',
            index=models.Index(fields=['metodo', 'status'], name='pf_stone_pag_met_st_idx'),
        ),
        migrations.AddIndex(
            model_name='stoneeventopagamento',
            index=models.Index(fields=['pagamento', 'created_at'], name='pf_stone_ev_pag_idx'),
        ),
    ]
