# Generated by Django 6.1 on 2026-08-20 17:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome do insumo')),
                ('category', models.CharField(choices=[('dtf_textil', 'DTF Têxtil'), ('dtf_uv', 'DTF UV'), ('camisas', 'Camisetas'), ('outros', 'Outros Insumos')], db_index=True, default='dtf_textil', max_length=30, verbose_name='categoria')),
                ('unit', models.CharField(choices=[('unidade', 'Unidade(s)'), ('metro', 'Metros (m)'), ('rolo', 'Rolo(s) / Bobina(s)'), ('litro', 'Litro(s)'), ('ml', 'Mililitros (ml)'), ('frasco', 'Frasco(s)'), ('kg', 'Quilogramas (kg)'), ('pacote', 'Pacote(s)')], default='unidade', max_length=20, verbose_name='unidade de medida')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='quantidade em estoque')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Avisar quando o saldo atingir ou ficar abaixo deste valor.', max_digits=10, verbose_name='estoque mínimo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Insumo de Estoque',
                'verbose_name_plural': 'Insumos de Estoque',
                'db_table': 'pf_supplies',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'name'], name='pf_supplies_cat_name')],
            },
        ),
        migrations.CreateModel(
            name='SupplyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada (Compra / Reposição)'), ('saida', 'Saída (Consumo / Produção)'), ('ajuste', 'Ajuste / Inventário')], default='entrada', max_length=20, verbose_name='tipo de movimentação')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantidade movimentada')),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='saldo anterior')),
                ('new_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='novo saldo')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='motivo / observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.supplyitem', verbose_name='insumo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_movements', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'pf_supply_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
