<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php';require_admin();
$filters=['inicio'=>$_GET['inicio']??date('Y-m-01'),'fim'=>$_GET['fim']??date('Y-m-d'),'etapa'=>(string)($_GET['etapa']??''),'pagamento'=>(string)($_GET['pagamento']??''),'funcionario'=>(int)($_GET['funcionario']??0),'prioridade'=>(string)($_GET['prioridade']??'')];
$where=['DATE(p.created_at) BETWEEN ? AND ?'];$params=[$filters['inicio'],$filters['fim']];if(valid_enum($filters['etapa'],production_labels())){$where[]='p.etapa=?';$params[]=$filters['etapa'];}if(valid_enum($filters['pagamento'],payment_labels())){$where[]='p.status_pagamento=?';$params[]=$filters['pagamento'];}if($filters['funcionario']){$where[]='p.responsavel_id=?';$params[]=$filters['funcionario'];}if(in_array($filters['prioridade'],['normal','urgente'],true)){$where[]='p.prioridade=?';$params[]=$filters['prioridade'];}$condition=implode(' AND ',$where);
$sql='SELECT p.*,u.nome responsavel_nome FROM pedidos p LEFT JOIN usuarios u ON u.id=p.responsavel_id WHERE '.$condition.' ORDER BY p.created_at DESC';$stmt=db()->prepare($sql);$stmt->execute($params);$orders=$stmt->fetchAll();
if(($_GET['exportar']??'')==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="relatorio-print-fornece-'.date('Ymd').'.csv"');$out=fopen('php://output','w');fprintf($out,"\xEF\xBB\xBF");fputcsv($out,['Número','Cliente','WhatsApp','Valor total','Valor pago','Pagamento','Etapa','Prioridade','Responsável','Criado em'],';');foreach($orders as $o)fputcsv($out,[$o['numero'],$o['cliente_nome'],$o['cliente_whatsapp'],number_format($o['valor_total'],2,',','.'),number_format($o['valor_pago'],2,',','.'),payment_labels()[$o['status_pagamento']],production_labels()[$o['etapa']],$o['prioridade'],$o['responsavel_nome'],date_br($o['created_at'],true)],';');fclose($out);exit;}
$active=array_filter($orders,fn($o)=>$o['etapa']!=='cancelado');$paid=array_sum(array_map(fn($o)=>(float)$o['valor_pago'],$active));$pending=array_sum(array_map(fn($o)=>max(0,(float)$o['valor_total']-(float)$o['valor_pago']),$active));$completed=count(array_filter($orders,fn($o)=>$o['etapa']==='finalizado'));$canceled=count(array_filter($orders,fn($o)=>$o['etapa']==='cancelado'));$ticket=count($active)?array_sum(array_map(fn($o)=>(float)$o['valor_total'],$active))/count($active):0;$expStmt=db()->prepare('SELECT COALESCE(SUM(valor),0) FROM despesas WHERE status="ativa" AND data_despesa BETWEEN ? AND ?');$expStmt->execute([$filters['inicio'],$filters['fim']]);$expenses=(float)$expStmt->fetchColumn();
$stageDurations=[];foreach(['novo','preparacao','producao','pronto'] as $stage){$q=db()->prepare('SELECT AVG(TIMESTAMPDIFF(MINUTE, h.created_at, COALESCE((SELECT MIN(h2.created_at) FROM pedido_etapas_historico h2 WHERE h2.pedido_id=h.pedido_id AND h2.created_at>h.created_at), NOW())) ) FROM pedido_etapas_historico h JOIN pedidos p ON p.id=h.pedido_id WHERE h.etapa_nova=? AND '.$condition);$q->execute(array_merge([$stage],$params));$min=(float)$q->fetchColumn();$stageDurations[$stage]=$min?round($min/60,1):null;}
$users=db()->query('SELECT id,nome FROM usuarios WHERE ativo=1 ORDER BY nome')->fetchAll();$page_title='Relatórios';require_once __DIR__ . '/../includes/header.php';$exportUrl='?'.http_build_query(array_merge($filters,['exportar'=>'csv']));
?>
<div class="section-heading"><div><h2>Resultados do período</h2><p>Valores pagos consideram pagamentos parciais e integrais; cancelados ficam fora dos totais financeiros.</p></div><div class="button-row no-print"><a class="btn btn-secondary" href="<?=$exportUrl?>"><i class="fa-solid fa-file-csv"></i> Exportar CSV</a><button class="btn btn-primary" onclick="window.print()"><i class="fa-solid fa-print"></i> Imprimir</button></div></div>
<form class="card filters no-print" method="get"><label>Data inicial<input type="date" name="inicio" value="<?=e($filters['inicio'])?>"></label><label>Data final<input type="date" name="fim" value="<?=e($filters['fim'])?>"></label><label>Etapa<select name="etapa"><option value="">Todas</option><?php foreach(production_labels() as $k=>$v):?><option value="<?=e($k)?>" <?=$filters['etapa']===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>Pagamento<select name="pagamento"><option value="">Todos</option><?php foreach(payment_labels() as $k=>$v):?><option value="<?=e($k)?>" <?=$filters['pagamento']===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>Funcionário<select name="funcionario"><option value="">Todos</option><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=$filters['funcionario']==$u['id']?'selected':''?>><?=e($u['nome'])?></option><?php endforeach;?></select></label><label>Prioridade<select name="prioridade"><option value="">Todas</option><option value="normal" <?=$filters['prioridade']==='normal'?'selected':''?>>Normal</option><option value="urgente" <?=$filters['prioridade']==='urgente'?'selected':''?>>Urgente</option></select></label><button class="btn btn-secondary btn-small">Aplicar</button></form>
<div class="grid stats-grid"><div class="stat-card"><small>Total de pedidos</small><strong><?=count($orders)?></strong></div><div class="stat-card"><small>Faturamento pago</small><strong><?=money($paid)?></strong></div><div class="stat-card alert"><small>Valor pendente</small><strong><?=money($pending)?></strong></div><div class="stat-card danger"><small>Despesas</small><strong><?=money($expenses)?></strong></div><div class="stat-card"><small>Lucro líquido</small><strong><?=money($paid-$expenses)?></strong></div><div class="stat-card"><small>Ticket médio</small><strong><?=money($ticket)?></strong></div><div class="stat-card"><small>Concluídos</small><strong><?=$completed?></strong></div><div class="stat-card danger"><small>Cancelados</small><strong><?=$canceled?></strong></div></div>
<section class="card card-pad"><div class="section-heading"><h2>Tempo médio em cada etapa</h2><p>Calculado a partir do histórico de movimentações.</p></div><div class="detail-grid"><?php foreach($stageDurations as $stage=>$hours):?><div><small><?=e(production_labels()[$stage])?></small><strong><?= $hours===null?'Sem dados':number_format($hours,1,',','.').' h'?></strong></div><?php endforeach;?></div></section>
<section class="card card-pad"><div class="section-heading"><h2>Pedidos detalhados</h2><p><?=count($orders)?> resultado(s)</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Número</th><th>Cliente</th><th>Data</th><th>Total</th><th>Pago</th><th>Etapa</th><th>Responsável</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><a class="text-green" href="<?=e(url('producao/detalhes.php?id='.$o['id']))?>"><?=e($o['numero'])?></a></td><td><?=e($o['cliente_nome'])?></td><td><?=date_br($o['created_at'],true)?></td><td><?=money($o['valor_total'])?></td><td><?=money($o['valor_pago'])?></td><td><?=status_badge($o['etapa'])?></td><td><?=e($o['responsavel_nome']?:'—')?></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="7"><div class="empty-state">Nenhum pedido no filtro selecionado.</div></td></tr><?php endif;?></tbody></table></div></section>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
