<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/auth.php';require_admin();
if(is_post()){
  validate_csrf($_POST['csrf_token']??null);$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);$actor=current_user();
  try{if($action==='save'){$name=trim((string)($_POST['nome']??''));$email=filter_var(trim((string)($_POST['email']??'')),FILTER_VALIDATE_EMAIL);$role=(string)($_POST['perfil']??'funcionario');$password=(string)($_POST['senha']??'');if(mb_strlen($name)<3||!$email||!in_array($role,['administrador','funcionario'],true))throw new RuntimeException('Informe nome, e-mail e perfil válidos.');if(!$id&&strlen($password)<8)throw new RuntimeException('A senha inicial deve ter pelo menos 8 caracteres.');if($id){$s=db()->prepare('SELECT * FROM usuarios WHERE id=?');$s->execute([$id]);$before=$s->fetch();if(!$before)throw new RuntimeException('Usuário não encontrado.');$dupe=db()->prepare('SELECT id FROM usuarios WHERE email=? AND id<>?');$dupe->execute([$email,$id]);if($dupe->fetch())throw new RuntimeException('Este e-mail já está em uso.');$sql='UPDATE usuarios SET nome=?,email=?,perfil=?';$params=[$name,$email,$role];if($password!==''){if(strlen($password)<8)throw new RuntimeException('A nova senha precisa ter 8 caracteres ou mais.');$sql.=',senha=?,forcar_troca_senha=1';$params[]=password_hash($password,PASSWORD_DEFAULT);}$sql.=' WHERE id=?';$params[]=$id;db()->prepare($sql)->execute($params);audit('edicao','usuario',$id,$before,['nome'=>$name,'email'=>$email,'perfil'=>$role]);flash('success','Usuário atualizado.');}else{$dupe=db()->prepare('SELECT id FROM usuarios WHERE email=?');$dupe->execute([$email]);if($dupe->fetch())throw new RuntimeException('Este e-mail já está em uso.');db()->prepare('INSERT INTO usuarios (nome,email,senha,perfil,forcar_troca_senha) VALUES (?,?,?,?,1)')->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]);$id=(int)db()->lastInsertId();audit('criacao','usuario',$id,null,['nome'=>$name,'email'=>$email,'perfil'=>$role]);flash('success','Usuário criado. Ele deverá trocar a senha no primeiro acesso.');}}
  elseif($action==='toggle'){$s=db()->prepare('SELECT * FROM usuarios WHERE id=?');$s->execute([$id]);$target=$s->fetch();if(!$target)throw new RuntimeException('Usuário não encontrado.');if($id===$actor['id']&&$target['ativo'])throw new RuntimeException('Você não pode desativar sua própria conta.');if($target['perfil']==='administrador'&&$target['ativo']){$admins=db()->query("SELECT COUNT(*) FROM usuarios WHERE perfil='administrador' AND ativo=1")->fetchColumn();if((int)$admins<=1)throw new RuntimeException('Mantenha ao menos um administrador ativo.');}$new=$target['ativo']?0:1;db()->prepare('UPDATE usuarios SET ativo=? WHERE id=?')->execute([$new,$id]);audit($new?'ativacao':'desativacao','usuario',$id,['ativo'=>$target['ativo']],['ativo'=>$new]);flash('success','Status do usuário atualizado.');}
  else throw new RuntimeException('Ação inválida.');
  }catch(PDOException $e){error_log('Usuário SQL: '.$e->getMessage());flash('error','Não foi possível salvar: verifique se o e-mail já existe.');}catch(Throwable $e){flash('error',$e instanceof RuntimeException?$e->getMessage():'Não foi possível atualizar o usuário.');}redirect('admin/usuarios.php');
}
$edit=null;if(!empty($_GET['editar'])){$s=db()->prepare('SELECT * FROM usuarios WHERE id=?');$s->execute([(int)$_GET['editar']]);$edit=$s->fetch()?:null;}$users=db()->query('SELECT id,nome,email,perfil,ativo,ultimo_acesso,created_at FROM usuarios ORDER BY ativo DESC,nome')->fetchAll();$page_title='Usuários';require_once __DIR__ . '/../includes/header.php';
?>
<div class="grid two-col"><section class="card form-card"><div class="section-heading"><div><h2><?=$edit?'Editar usuário':'Novo usuário'?></h2><p>Senhas são armazenadas com hash seguro.</p></div></div><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0)?>"><div class="form-grid"><label>Nome<input name="nome" value="<?=e($edit['nome']??'')?>" required></label><label>E-mail<input type="email" name="email" value="<?=e($edit['email']??'')?>" required></label><label>Perfil<select name="perfil"><option value="funcionario" <?=($edit['perfil']??'')==='funcionario'?'selected':''?>>Funcionário</option><option value="administrador" <?=($edit['perfil']??'')==='administrador'?'selected':''?>>Administrador</option></select></label><label><?= $edit?'Nova senha (opcional)':'Senha inicial'?><input type="password" name="senha" <?=!$edit?'required minlength="8"':''?> minlength="8" autocomplete="new-password"><span class="help"><?= $edit?'Preencha para redefinir; o usuário deverá trocá-la no login.':'Mínimo de 8 caracteres; será solicitada nova senha no primeiro acesso.'?></span></label></div><div class="form-actions"><?php if($edit):?><a class="btn btn-secondary" href="<?=e(url('admin/usuarios.php'))?>">Cancelar edição</a><?php endif;?><button class="btn btn-primary">Salvar usuário</button></div></form></section><section class="card card-pad"><h2>Regras de acesso</h2><p class="text-muted">Administradores acessam todas as áreas. Funcionários trabalham com pedidos, produção, notificações e perfil; não acessam dados financeiros nem gestão de pessoas.</p></section></div>
<section class="card card-pad"><div class="section-heading"><h2>Equipe</h2><p><?=count($users)?> usuário(s)</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Cadastro</th><th class="no-print">Ações</th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><strong><?=e($u['nome'])?></strong><br><small class="text-muted"><?=e($u['email'])?></small></td><td><?=e(ucfirst($u['perfil']))?></td><td><?=$u['ativo']?'<span class="badge badge-pago">Ativo</span>':'<span class="badge badge-cancelado">Inativo</span>'?></td><td><?=date_br($u['ultimo_acesso'],true)?></td><td><?=date_br($u['created_at'])?></td><td class="no-print"><div class="button-row"><a class="btn btn-secondary btn-small" href="?editar=<?=$u['id']?>">Editar</a><form method="post"><?=csrf_input()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn <?=$u['ativo']?'btn-danger':'btn-secondary'?> btn-small" data-confirm="<?=$u['ativo']?'Desativar':'Ativar'?> este usuário?"><?=$u['ativo']?'Desativar':'Ativar'?></button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
