# Generated by Django 6.0.7 on 2026-08-16 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='relato do problema')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_reports/%Y/%m/', verbose_name='print / captura de tela')),
                ('current_url', models.CharField(blank=True, max_length=500, verbose_name='tela / rota onde ocorreu')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de análise pelo Dev'), ('verificado', 'Verificado'), ('corrigido', 'Corrigido')], db_index=True, default='pendente', max_length=30, verbose_name='situação')),
                ('dev_notes', models.TextField(blank=True, verbose_name='anotações técnicas do Dev')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Relato de Bug',
                'verbose_name_plural': 'Relatos de Bugs',
                'db_table': 'pf_bug_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pf_bug_status_created'), models.Index(fields=['user', 'created_at'], name='pf_bug_user_created')],
            },
        ),
    ]
