# Generated by Django 6.0.7 on 2026-07-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='ação')),
                ('entity', models.CharField(max_length=80, verbose_name='entidade')),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='identificador da entidade')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='dados anteriores')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='dados posteriores')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_audit_events',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['entity', 'entity_id', 'created_at'], name='pf_audit_entity_time'), models.Index(fields=['user', 'created_at'], name='pf_audit_user_time')],
            },
        ),
    ]
