# Generated by Django 6.0.7 on 2026-07-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('pedido', 'Pedido'), ('financeiro', 'Financeiro'), ('sistema', 'Sistema')], default='pedido', max_length=15)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pf_notifications',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='pf_notification_read')],
            },
        ),
    ]
